igt-gpu-tools: add procps-lib to RDEPENDS
Build error occurs as below:

  ERROR: igt-gpu-tools-1.25+gitAUTOINC+d16ad07e7f-r0 do_package_qa:
         QA Issue: /usr/lib/libigt.so.0 contained in package igt-gpu-tools
	 requires libprocps.so.8(LIBPROCPS_0)(64bit), but no providers
	 found in RDEPENDS_igt-gpu-tools? [file-rdeps]

Add procps-lib to RDEPENDS to solve this issue.

(From OE-Core rev: 9d6282ea314fff0d7df163b2634373640c468502)

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>