perf: fix build with latest kernel
Kernel commit 9eea8fafe33e ("libbpf: fix __arg_ctx type enforcement for
perf_event programs") added with 6.9-rc1 tools/include/uapi/asm/bpf_perf_event.h
which for arc, arm64, loongarch, riscv and s390 includes headers from
the arch/${ARCH}/... directories.
Thus the build in OE fails as those headers are not present.

Fix this by additioanly copying all files in arch/${ARCH}/include/.

Fixes:
ERROR: perf-1.0-r0 do_compile: oe_runmake failed
| In file included from work/verdin_imx8mm-tdx-linux/perf/1.0/perf-1.0/tools/include/uapi/linux/bpf_perf_event.h:11,
|                  from libbpf.c:36:
| work/verdin_imx8mm-tdx-linux/perf/1.0/perf-1.0/tools/include/uapi/asm/bpf_perf_event.h:2:10: fatal error: ../../arch/arm64/include/uapi/asm/bpf_perf_event.h: No such file or directory
|     2 | #include "../../arch/arm64/include/uapi/asm/bpf_perf_event.h"
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(From OE-Core rev: 40a7843a42d9b31ef2e4b19cf88a1d91a397cc11)

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>