nfs-utils: Fix do_configure when switching configurations
On the autobuilder we saw:
ERROR: nfs-utils-2.8.3-r0 do_package_qa: QA Issue: nfs-utils package is not obeying usrmerge distro feature. /lib should be relocated to /usr. [usrmerge]

This can be reproduced by running do_configure with sysvinit, switching to
systemd and re-running do_configure. udev_rulesdir will then have the wrong
value.

Fix the sed expressions so the task can rerun correctly and update as
desired.

(From OE-Core rev: e8d13f7f03273cdde15db279ca4f09b183450cb1)

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>